qri-io/starlib

math/math.go
math/math_test.go
math/testdata/test.sky
math/trig.go

@stuartlynn, this repo is our crack at a standard library for skylark (recently renamed to _starlark_). Qri makes any module defined here available with a starlark `load` statement. This PR adds some math primitives you'd asked for, I'd love your review to see if anything you need is missing.
Modules here are often implemented as thin wrappers around the go standard library, conformed wherever possible to standard / popular python modules. in this case the function names are almost the exact same between go & [python 3.7](https://docs.python.org/3/library/math.html).
If merged, you'd be able to do stuff like the following in Qri once we cut a release that includes the math module:
```python
load('math.sky', 'math')
math.cos(1.0)       # 0.5403023058681398
math.sin(1.0)       # …
```

feat(math): add initial math package

---

encoding/base64/base64.go
encoding/base64/base64_test.go
encoding/base64/testdata/test.star
html/html.go
html/html_test.go
html/testdata/test.star
http/http.go
http/http_test.go
http/testdata/test.star
math/math.go
math/math_test.go
math/testdata/test.star
re/re.go
re/re_test.go
re/testdata/test.star
time/testdata/test.star
time/time.go
time/time_test.go
xlsx/testdata/test.star
xlsx/xlsx.go
xlsx/xlsx_test.go
zipfile/testdata/test.star
zipfile/zip.go
zipfile/zip_test.go

builds on #6. This is a breaking change that modifies the name of all package imports

refactor(.star): Complete conversion to .star, starlark name switch

---

encoding/csv/csv.go
encoding/csv/doc.go
makefile

[wolrld bank](https://data.worldbank.org/indicator/SP.POP.TOTL) outputs shitty csv data. need moar params to tune `read_all`. make less shitty. This PR brings `read_all` up to configuration-parity with the golang version it's built on.
I want to stick with `read_all` for now until we have a discussion about readers & writers in starlark.

feat(csv.read_all): add parameters for tuning csv.read_all

---

geo/doc.go
geo/geo.go
geo/geo_test.go
geo/geojson.go
geo/line.go
geo/multi_polygon.go
geo/point.go
geo/polygon.go
geo/template.html
geo/testdata/test.star
makefile
starlib.go

This PR take a very large bite out of [RFC0015](https://github.com/qri-io/rfcs/blob/master/text/0000-add-geo-processing-abilities-to-skylark.md). I keep working on datasets, and keep needing geo functions. Having played with this branch in it's current state I'm confident there are _many_ uses for this module 😄. That, and lots of the people we're working with right now would use this package if it existed.
** **
For this PR I focused on getting the example transform script from the RFC to work. here's what the adapted code ended up looking like:
```python
load("http.star", "http")
load("geo.star", "geo")
def download(ctx):
complaints = http.get("https://data.cityofnewyork.us/resource/fhrw-4uyv.json?$offset=0&$limit=10000")
boros = …
```

feat(geo): add geo module

---

encoding/csv/csv.go
encoding/json/doc.go
encoding/json/json.go
encoding/json/json_test.go
encoding/json/testdata/test.star
starlib.go

get started nice & easy with an API that matches python's `json` package: https://docs.python.org/3/library/json.html
closes #19 
** **
outline:
json provides functions for working with json data
serialize obj to a JSON string
**parameters:**
| name | type | description |
|------|------|-------------|
| `obj` | `object` | input object |
read a source JSON string to a starlark object
**parameters:**
| name | type | description |
|------|------|-------------|
| `source` | `string` | input string of json data |

feat(json): add initial json package

---

util/util.go
util/util_test.go

I was working on a `encoding/yaml` module and I found that `util.Marshal` lacks some types support. I added the coverage of this types plus a test for it.
Also I believe that can be useful introduce support for an interface like:
```go
type StarkarkMarshaller interface {
AsStarlark() starlark.Value
}
```
To allow conversion from any type and not just the standard ones.

feat(starlib): util.Marshal extended compatibility and tests

---

time/doc.go
time/testdata/test.star
time/time.go

These methods make it easy to display the current time in a given
location and in a desired format. For example:
time.now().in_location("US/Pacific").format("3:04 PM")

feat(time): Add in_location and format methods

---

README.md
bsoup/README.md
bsoup/doc.go
html/README.md
html/doc.go

Typos, corrections, generated bsoup README.md.
Corrected /html/README.md before I saw that it was autogenerated. But it matches the regenerated README.md, so it doesn’t show up in the diff after regeneration.

Typos corrections

---

time/doc.go
time/testdata/test.star
time/time.go

This allows converting a time object to a unix timestamp.

feat(time): Add unix and unix_nano methods

---

go.mod
go.sum
util/util.go
util/util_test.go

- Added support custom type (Unmarshaler\Marshaler) #48
- Added more tests for util
- Fixed some bugs
- Refactoring unmarshal `starlark.Dict` if exists key as a not string

Added support custom type and fixed bugs

---

time/doc.go
time/testdata/test.star
time/time.go

`time.fromtimestamp` parses a Unix timestamp integer to a time.time object
Based on the [`datetime.fromtimestamp()`](https://docs.python.org/3/library/datetime.html#datetime.date.fromtimestamp) method in Python
Example:
```python
assert.eq(time.time("2020-06-26T17:38:36Z"), time.fromtimestamp(1593193116))
```

feat(time): Add fromtimestamp method

---

go.mod
go.sum
time/doc.go
time/testdata/test.star
time/time.go

Allow for formating times using C-style strftime format strings
Example:
```
assert.eq(time.time("2020-06-26T17:38:36Z").strftime("%Y"), "2020")
assert.eq(time.time("2020-06-26T17:38:36Z").strftime("%F %R"), "2020-06-26 17:38")
```
Introduces a dependency on [gostrftime](https://godoc.org/github.com/cactus/gostrftime). Chosen because it is the most popular strftime library on godoc.org ([source](https://godoc.org/?q=strftime)).

feat(time): Add strftime method to time instances

---

util/util.go
util/util_test.go

An example of how I was using this:
```py
x = {
'time': time.fromtimestamp(1588540633),
'int': 123
}
```
```go
// main.go
contents, err := starlark.ExecFile(thread, "test.star", nil, nil)
unmarshaled, err := util.Unmarshal(contents["x"])
switch unmarshaled["x"]["time"].(type) {
case time.Time:
y := unmarshaled["x"]["time"].(time.Time)
...
default:
return errors.New("unrecognized type")
}
```
Without the patch in this PR, the example returns `unrecognized type` error. Further, without using `util.Unmarshal`, eventual a confusing error appears because the type of `contents["x"]["time"]` prints as `time.Time` even though it is different from a go `time.Time` and go's `time.Time` functions do not work with this object. With this patch, it returns as expected.

feat(util): unmarshal/marshal for starlib/time.Time to go's standard time.Time

---

http/doc.go
http/http.go
http/http_test.go

Add the `form_encoding` parameter to HTTP methods. When it is set to
`application/x-www-form-urlencoded`, encode form data as a string of
key-value pairs. This is the same encoding as Go's `http.PostForm`.

feat(http): support URL encoding for forms

---

time/testdata/test.star
time/time.go

Since `time(some_str)` assumes that `some_str` is in RFC3339 format, make
`str(time)` output a string in that format. This gives us the very
useful new property that `time(str(some_time)) == some_time`.

feat(time): make string representation reversible

---

go.sum
http/http_test.go
util/util.go
util/util_test.go

`starlark.Tuple` is actually just an alias for `[]starlark.Value`. So
when a Starlark function returns a tuple, it is a `starlark.Tuple` and
not `*starlark.Tuple`.

fix(util): handle tuples correctly

---

time/testdata/test.star
time/time.go

Calling .String() on location produces a quoted string, resulting
an error from LoadLocation().

fix(time): fix location parsing in time()

---

hash/README.md

Should be hash instead of time.

Fix typo in the hash module's README.md

---

math/doc.go
starlib.go
time/doc.go

hotfix for a mistake in the way imports should work. based on tests in go-starlark, we're keeping the .star suffix apparently. This restores import paths to their prior (non-breaking between releases) versions:
`load("time", "time")` -> `load("time.star", "time")`
`load("math", "time")` -> `load("math.star", "time")`
package APIs are still locked to the upstream time & math modules

fix(math,time): restore ".star" suffixes to math & time modules

---

util/util.go
util/util_test.go

Had to also change marshaling tests to use Starlark's `Equal` instead of just comparing by value (it doesn't work for big integers).

Fix unmarshaling of 64 bit integers

---

dataframe/convert.go
dataframe/dataframe.go
dataframe/dataframe_test.go
dataframe/index.go
dataframe/index_test.go
dataframe/series.go
dataframe/series_test.go
dataframe/string_methods.go
dataframe/testdata/dataframe_basic.expect.txt
dataframe/testdata/dataframe_basic.star
dataframe/testdata/dataframe_columns.expect.txt
dataframe/testdata/dataframe_columns.star
dataframe/testdata/dataframe_getkey.expect.txt
dataframe/testdata/dataframe_getkey.star
dataframe/testdata/dataframe_setkey.expect.txt
dataframe/testdata/dataframe_setkey.star
dataframe/testdata/index.star
dataframe/testdata/series_basic.expect.txt
dataframe/testdata/series_basic.star
dataframe/testdata/series_index_name.expect.txt
dataframe/testdata/series_index_name.star
dataframe/typed_array_builder.go
dataframe/typed_slice_builder.go
go.sum

Index is used to store axis labels for Series and DataFrame. It has a name, and can be stringified. The text values in an index can be manipulated using stringMethods. A Series with an Index with a name will stringify with that name.
DataFrame exists, but only has a bit of functionality. It has columns, which are an index. It has an index which stringifies. DataFrame columns can be get'ed or set'ed, using Series objects. DataFrame can be constructed using a list or dict.
Build the series contents using a builder that handles all type coercion. This allows DataFrame to retain its actual input types. Series now handles boolean types.

Index and basic DataFrame with columns

---

dataframe/convert.go
dataframe/dataframe.go
dataframe/dataframe_test.go
dataframe/series.go
dataframe/series_test.go
dataframe/test_runner_test.go
dataframe/testdata/dataframe_bool_select.expect.txt
dataframe/testdata/dataframe_bool_select.star
dataframe/testdata/dataframe_bool_select_failure.star
dataframe/testdata/series_attrs.expect.txt
dataframe/testdata/series_bool_select.expect.txt
dataframe/testdata/series_bool_select.star

This type of operation is now supported:
```
res = df[df['type'].equals('important')]
```
Detect this invalid operation and display a helpful error message:
```
res = df[df['type'] == 'important']
```

feat(dataframe): Select rows from a dataframe using a bool series

---

dataframe/dataframe.go
dataframe/dataframe_test.go
dataframe/testdata/dataframe_head.star
dataframe/testdata/dataframe_read_csv.star

Prior to this, read_csv would parse csv from text. This was different from the pandas.DataFrame implementation, which would require a url to be passed to read_csv. This difference caused confusion. In the future, once the story around http access is fixed, the read_csv will be restored to match the pandas version.

feat(dataframe): parse_csv to parse csv from text

---

html/doc.go
html/html.go
html/testdata/test.star

Using the `html` package, I needed a way to get the type of an element in a `selection`.  `goquery` has an `Is()` method which returns a bool if the selection includes a selector passed in as a string.
This PR adds `isSelector()` as a method on `structure`, because `is()` seems to be reserved (or at least when I tried using `is()` I got "not an identifier" errors, which cleared up when I used any other name).

feat: add Is() as isSelector()

---

compress/gzip/doc.go
encoding/csv/doc.go
encoding/json/doc.go
hash/doc.go

- removes some `sed` commands that were clearing subdirectories for docs pages (makefile will now write the corresponding markdown in a subdirectory if the source file is in a subdirectory, e.g. encoding/csv will end up in `/encoding/csv.md` instead of in the root of the starlib docs)
- adds missing indentations to `outline` documentation code, which was causing issues with display in the docs site.  This is a bug documented here: https://github.com/b5/outline/issues/5

starlib docs cleanup

---

asset/doc_template.txt

Replaces `<code>` tags with 3 backticks in the template used to generate docs markdown files.  This ensures they will be parsed properly when the qri website is built.

Use backticks for code

---

http/http.go

Update the signature of `RequestGuard.Allowed` to accept a pointer to
the current Starlark thread, and to return an `*http.Request`.
This allows a `RequestGuard` implementation to modify the HTTP request
before it is executed, and to do so on a per-thread basis if desired.

feat(http): allow RequestGuard to modify request

---

dataframe/dataframe_test.go
dataframe/testdata/dataframe_type_keep.expect.txt
dataframe/testdata/dataframe_type_keep.star
dataframe/typed_slice_builder.go

Doing this is necessary to have correct logic when `push`ing to the builder. This ends up fixing a segfault that may be seen in the test case `dataframe_type_keep`

fix(dataframe): When adding to a series, retain the existing type

---

dataframe/dataframe.go
dataframe/testdata/dataframe_append.expect.txt
dataframe/testdata/dataframe_append.star

Before, df = df.append(item) required item to be a starlark.List. With this change, it may also be another DataFrame.

fix(dataframe): Append works with DataFrame args

---

asset/doc_template.txt

Updates `doc_template`, defining a new template called `mdFnChild` which allows for proper nesting/hierarchy for `method`s that appear below a `Type` by making the method title an h4 instead of an h4, and its child headings h5 instead of h4.
This is necessary so that when rendered in our docs page, the `append` method of `Dataframe` appears smaller and lower in importance than its parent.  (Before they were rendered with the same level of importance, causing confusion)
.

feat: allow proper nesting of methods under types

---

dataframe/dataframe.go
dataframe/series.go
dataframe/testdata/dataframe_append.expect.txt
dataframe/testdata/dataframe_append.star

In order to avoid potential segfaults, we must ensure that DataFrames always have a tabular body; that each column has the same height. Use a single constructor everywhere that enforces this rule, as well as the existence of an OutputConfig. Update the append method so that rows of different sizes are handled correctly, by padding them with None values.

fix(dataframe): Invariant that body is tabular, OutputConfig exists

---

dataframe/dataframe.go
dataframe/math.go
dataframe/series.go
dataframe/series_test.go
dataframe/testdata/series_math.expect.txt
dataframe/testdata/series_math.star

Series can be added and subtracted to each other. Finally, we get to take advantage of the series struct storing slices of ints and floats by accessing them directly in a loop. Add a `dataframe.abs` function, which takes the `abs` of an entire series, one element at a time. Due to starlark's lack of ability to override builtins, we can't use the standard `abs` function.

feat(dataframe): Series math operations: add, subtract, abs

---

dataframe/dataframe.go
dataframe/dataframe_test.go
dataframe/series.go
dataframe/test_runner_test.go
docs_test.go

Multiple bugs existed with OutputConfig, but their behavior masked each other. Validate that the supplied OutputConfig is non-nil, use a constant for the key name, and fix tests so that they ensure the intended behavior. Supply an exported function for callers to set their own OutputConfig.

fix(dataframe): Fix OutputConfig bugs

---

dataframe/convert.go
dataframe/dataframe.go
dataframe/series.go
dataframe/series_test.go
dataframe/test_runner_test.go
dataframe/testdata/series_time.expect.txt
dataframe/testdata/series_time.star
dataframe/typed_slice_builder.go

Dataframe and Series now allow time.Time objects. Can be added as values, instead of needing to be represented as strings. Timestamps are now stored as ints, using the dtype 'datetime64[ns]'.
The `astype` method no longer needs to parse when converting ints to timestamps or vice versa.

feat(dataframe): First class support for timestamp values

---

time/doc.go

The docs had this function listed as `parse_time` when in reality it is `parseTime`.

Fix capitalization of parse_time function

---

http/http.go

Added specification of Content-Length during creation of the Request Body for URL Encoded and JSON Encoded content.   
The existing implementation uses the ioutil.NopCloser method to create the Request body, which triggers ShouldSendChunkedRequestBody in https://go.dev/src/net/http/transfer.go that results in the Request Header specifying Transfer-Encoding: Chunked.
This change enables compatibility with Endpoints (such as Microsoft Graph APIs) that do not support Transfer-Encoding: Chunked
Testing: I've rebuilt the new http.go library into the Pixlet application: https://github.com/tidbyt/pixlet and hit multiple endpoints at Google and MSFT cloud with successful result (about 10 different API calls)

Ensure Content-Length is Sent
